[build]
  publish = "book/"
  command = "npm i -g prettier@2.3.2 && prettier --check --prose-wrap always '**/*.md' && curl -L https://github.com/rust-lang/mdBook/releases/download/v0.4.7/mdbook-v0.4.7-x86_64-unknown-linux-gnu.tar.gz | tar xvz && ./mdbook build"
